defaults:
  - general
  - dataset: ???
  - model: rnndet
  - _self_

checkpoint: checkpoints/RVT_DSEC.ckpt
use_test_set: False
hardware:
  num_workers:
    eval: 6
  gpus: 0 # GPU idx (multi-gpu not supported for validation)
batch_size:
  eval: 4
training:
  precision: 16
